from setuptools import setup

setup(name='Okonf',
      version='0.1.0',
      description=' Experimental configuration management based on Python Asyncio',
      long_description=open('README.md').read(),
      author='Hugo Herter',
      author_email='@hugoherter.com',
      url='https://github.com/hoh/Okonf/',
      packages=['okonf', 'okonf.connectors', 'okonf.contracts', 'okonf.facts'],
      entry_points={'console_scripts': ['okonf=okonf.__main__:run']},
      install_requires=['asyncssh', 'pylxd', 'aiohttp'],
      license='Apache License 2.0',
      keywords="configuration management",
      classifiers=['Development Status :: 2 - Pre-Alpha',
                   'Environment :: Console',
                   'Programming Language :: Python :: 3',
                   'Intended Audience :: Developers',
                   'Intended Audience :: System Administrators',
                   'Intended Audience :: Information Technology',
                   'Natural Language :: English',
                   'Operating System :: POSIX :: Linux',
                   'License :: OSI Approved :: Apache Software License',
                   'Topic :: System :: Installation/Setup',
                   'Topic :: System :: Systems Administration',
                   ],
)